### ISSUE TITLE
комментарий 1

### ISSUE THREAD

**Issue by oldSorcerer** [denik5/Cryptographer#1]
src/CaesarCipher.java
убери все статик и main в этом классе они не нужны

**Comment by denik5** [comment]
принял!

Отправлено из мобильной Почты Mail.ru

Tuesday, 16 January 2024 at 15:19 +03:00 from ***@***.***  ***@***.***>:

**Comment by oldSorcerer** [comment]
Вижу что справил 
issues можно закрывать
